LOGIN_MESSAGE = 'You are login successfully'
SUCCESS_RESPONSE_MESSAGE = 'Ok'
ERROR_RESPONSE_MESSAGE = "error"
API_RESPONSE = 'response'

RESPONSE_DATA = 'data'

LOGIN_MESSAGE_JSON = {
    'message': LOGIN_MESSAGE,
    API_RESPONSE: SUCCESS_RESPONSE_MESSAGE
}

BODY_NOT_BLANK_JSON = {
    "message":"body can not be blank.",
    API_RESPONSE: ERROR_RESPONSE_MESSAGE
}
