# Generated by Django 5.1.1 on 2024-09-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='no_of_albums_released',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
