# Generated by Django 5.1.1 on 2024-09-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_updated_at_alter_song_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
